name: Deploy Static Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Replace secret in JS
      run: |
        sed -i 's/YOUR_SECRET_HERE/${{ secrets.MY_SECRET }}/' script.js
        cat script.js # הדפסת התוכן של script.js ללוג

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .